# ========================================
# TazAntixRAY Configuration
# ========================================
# Advanced Anti-XRay plugin for Folia
# Developed by TazukiVN
# Version: 1.2.1
# ========================================

# ========================================
# GENERAL SETTINGS
# ========================================
settings:
  # Language for messages (en, vi, es, fr, de, etc.)
  # Language files are located in plugins/TazAntixRAY/lang/
  language: "en"

  # Enable debug mode for detailed logging
  # Set to true for troubleshooting, false for production
  debug-mode: false

  # Refresh cooldown in seconds to prevent lag from rapid Y-level changes
  # Higher values = less lag but slower updates
  # Lower values = faster updates but potential lag
  refresh-cooldown-seconds: 3

  # View distance for chunk refreshing (in chunks)
  # Uses server view distance if not specified
  # view-distance: 10

# ========================================
# WORLD CONFIGURATION
# ========================================
worlds:
  # List of worlds where anti-xray is active
  # Add world names exactly as they appear in your server folder
  whitelist:
    - "world"
    - "mining_world"
    # - "survival_world"
    # - "resource_world"

  # IMPORTANT: Avoid adding these world types:
  # - Nether worlds (world_nether)
  # - End worlds (world_the_end)
  # - Creative worlds
  # These can cause visual glitches or performance issues

# ========================================
# ANTI-XRAY SETTINGS
# ========================================
antixray:
  # Y-level threshold for anti-xray protection
  # When player is ABOVE this level: Hide everything below hide-below-y
  # When player is AT or BELOW this level: Show everything normally
  # This replaces the old trigger-y-level and stop-hiding-y settings
  protection-y-level: 31.0

  # Y-level below which blocks/entities are hidden (when protection is active)
  # All blocks and entities at this Y-level and below will be hidden
  hide-below-y: 16

  # Transition zone settings
  transition:
    # Enable smooth transition between hidden and visible states
    smooth-transition: true

    # Transition zone size (blocks above hide-below-y where effect gradually reduces)
    transition-zone-size: 5

# ========================================
# PERFORMANCE SETTINGS
# ========================================
# Performance settings are automatically optimized for your platform
# Folia optimizations are automatically enabled when running on Folia
performance:
  # Maximum chunks to process per tick (automatically adjusted per platform)
  max-chunks-per-tick: 50

  # Maximum entities to process per tick
  max-entities-per-tick: 100

  # Instant protection settings - load large area immediately
  instant-protection:
    enabled: true
    # Load this many chunks radius instantly when player approaches Y16
    instant-load-radius: 15
    # Pre-load protection when player is this many blocks above Y16
    pre-load-distance: 10
    # Force immediate chunk refresh (prevents seeing bases)
    force-immediate-refresh: true

  # Limit the anti-xray effect to a small area around the player
  limited-area:
    enabled: false
    # The radius in chunks around the player to apply the effect
    chunk-radius: 3
    # Only apply when the player is nearby
    apply-only-near-player: true

  # Block replacement settings
  replacement:
    # The block type used to replace hidden ores (e.g., "air", "deepslate", "stone")
    block-type: "air"

  # Entity hiding settings
  entities:
    # Hide all entities in hidden areas (true = hide, false = show)
    hide-entities: true

  # Complete underground protection
  underground-protection:
    # Hide everything below Y16 when player is ABOVE Y16
    # When player reaches Y16 or below: Show everything normally
    # This includes: blocks, entities, chests, etc.
    enabled: true

# ========================================
# ADVANCED SETTINGS
# ========================================
# Advanced settings, usually not necessary to change
advanced:
  # Packet processing to hide blocks more effectively
  packet-processing:
    modify-chunk-data: true
    modify-block-changes: true
    modify-multi-block-changes: true

  # How to handle player teleports
  teleport-handling:
    delay-ticks: 1
    manage-teleport-states: true

# ========================================
# COMPATIBILITY SETTINGS
# ========================================
compatibility:
  # Enable compatibility with other anti-xray plugins
  other-antixray-plugins: false

  # Enable compatibility with world management plugins
  world-management-plugins: true

  # Enable compatibility with permission plugins
  permission-plugins: true

# ========================================
# DO NOT MODIFY BELOW THIS LINE
# ========================================
# Configuration version for automatic updates
config-version: 1
