name: TazAntixRAY
version: '1.2.1'
main: com.tazukivn.tazantixray.TazAntixRAYPlugin
api-version: '1.20'
folia-supported: true
load: STARTUP
depend: [packetevents]
authors: [TazukiVN]
description: Advanced Anti-XRay plugin with multi-platform support (Folia, Paper, Spigot) for Minecraft 1.20-1.21.8+
website: https://github.com/TazukiVN/TazAntixRAY
softdepend: [Geyser, Floodgate]



commands:

  tazantixray:
    description: Main command for TazAntixRAY plugin.
    usage: /tazantixray <debug|reload|world|stats|entities|test> [args]
    permission: tazantixray.admin
    aliases: [tar, antixray]
  tardebug:
    description: Toggles debug mode for TazAntixRAY plugin.
    usage: /tardebug
    permission: tazantixray.debug
    aliases: [tazantixraydebug]
  tarreload:
    description: Reloads the TazAntixRAY configuration.
    usage: /tarreload
    permission: tazantixray.admin
    aliases: [tazantixrayreload]
  tarworld:
    description: Manages the world whitelist for TazAntixRAY.
    usage: /tarworld <list|add|remove> [worldName]
    permission: tazantixray.admin
    aliases: [tazantixrayworld]
permissions:
  tazantixray.admin:
    description: Allows access to TazAntixRAY admin commands.
    default: op
    children:
      tazantixray.debug: true
      tazantixray.world: true
      tazantixray.reload: true
  tazantixray.debug:
    description: Allows toggling of TazAntixRAY debug mode.
    default: op
  tazantixray.world:
    description: Allows managing world whitelist for TazAntixRAY.
    default: op
  tazantixray.reload:
    description: Allows reloading TazAntixRAY configuration.
    default: op